.github/pull_request_template.md

We were referring to `Clubhouse` as our ticket tracking system in the pull request template, but we're using GitHub projects
Update template to use a placeholder link for github

fix: change from ch to gh link in pr template

---

test/src/utils/exceptions_test.dart

[GitHub Project Card](https://github.com/SupposedlySam/firefuel/projects/1#card-67669667)
No tests exist for the `MissingValueException` class yet
- Test the `toString` method of the `MissingValueException` class

test: MissingValueException

---

packages/firefuel_core/lib/src/models/document_id/document_id_model.dart
packages/firefuel_core/lib/src/serializable.dart
pubspec.lock
test/src/firefuel_repository_test.dart
test/src/utils/exceptions_test.dart
test/utils/test_user.dart

[Project Card Link](https://github.com/SupposedlySam/firefuel/projects/1#card-67891879)
For classes that already extended `Equatable` (such as freezed classes)
Equatable required to override the prop method, which may be unnecessary for some. Removing equatable allows (freezed) classes to only require the `toJson` method
Removed `Equatable` from `Serializable` class
Added `Equatable` to the `DocumentId` and `TestUser` classes

Removing Equatable from Serializable class

---

lib/src/firefuel_collection.dart
test/src/firefuel_collection_test.dart

[Project Card Link]()
- Errors existed when pulling down the branch
- Other changes can now be made
- rename `collectionName` to `collectionPath`
- rename `firestoreInstance` to `firestore` -- this will be used as a named argument in everyone's class, we should make it shorter
- change `untypedCollectionRef` into a `getter` instead of a method
- Sort members in `FirefuelCollection` class
- Make sure the `fromFirestore` function returns a nullable `T`
- Rename `value` to `model` and `document` to `snapshot` to follow the names we were using in our `collectionRef` method
- Move the `stream` class functionality into the `FirefuelCollection` class
- Update the test to use the new class changes and no longer have errors

fix: collection conversion update

---

lib/src/firefuel_collection.dart
test/src/firefuel_collection_test.dart

[Project Card Link: firefuelInstance](https://github.com/SupposedlySam/firefuel/projects/1#card-67968782)
[Project Card Link: collectionRef](https://github.com/SupposedlySam/firefuel/projects/1#card-67968759)
Simplify method to retrieve `collectionRef`.
Require the Firestore instance as constructor to use within the the `FirefuelCollection`.
Create `fromFirestore` and `toFirestore` that will be used as the methods to create the `collectionRef` getter.

feat: Create CollectionRef and Stream w/ (From|To)Firestore Methods

---

lib/src/collection.dart
lib/src/firefuel_collection.dart
test/src/firefuel_collection_test.dart

[Project Card Link](https://github.com/SupposedlySam/firefuel/projects/1#card-67877432)
- To follow CRUD's naming convention instead of Firestore's convention 
- Rename `getOrCreate` to `readOrCreate`

refactor!: renamed getOrCreate to readOrCreate

---

packages/firefuel/lib/firefuel.dart
packages/firefuel/lib/src/firefuel.dart
packages/firefuel/lib/src/firefuel_collection.dart
packages/firefuel/test/src/firefuel_collection_test.dart
packages/firefuel/test/src/firefuel_test.dart

[Project Card Link](https://github.com/SupposedlySam/firefuel/issues/13)
- Simplify the process to create a FirefuelCollection
- Provide `FirebaseFirestore.instance` to all instances of FirefuelCollection
- Create Firefuel class 
- Remove FirebaseFirestore param from FirefuelCollection constructor

feat!: FirebaseFirestore.instance

---

packages/firefuel/lib/src/collection.dart
packages/firefuel/lib/src/firefuel_collection.dart
packages/firefuel/test/src/firefuel_collection_test.dart

[Project Card Link](https://github.com/SupposedlySam/firefuel/projects/1#card-68316758)
Resolves Issue #15 
`collectionRef` and `collectionPath` were redundant since they were inside of the `Collection` class
Rename `collectionRef` to `ref` and `collectionPath` to `path`.

refactor!: drop collection prefix

---

analysis_options.yaml
packages/firefuel/lib/firefuel.dart
packages/firefuel/lib/src/collection.dart
packages/firefuel/lib/src/firefuel_collection.dart
packages/firefuel/lib/src/firefuel_repository.dart
packages/firefuel/lib/src/repository.dart
packages/firefuel/lib/src/rules.dart
packages/firefuel/pubspec.lock
packages/firefuel/pubspec.yaml
packages/firefuel/test/mocks/mock_collection.dart
packages/firefuel/test/src/firefuel_collection_test.dart
packages/firefuel/test/src/firefuel_repository_test.dart
packages/firefuel/test/src/firefuel_test.dart

[Project Card Link]()
Breaking up the Collection methods into smaller classes allows for more control over permissions by collection. Smaller abstract classes also allow us to specify a return type for each class individually, making it possible to share the rules classes between Collection and Repository
- Separate the Collection abstract class into multiple "rule" classes we can implement in both Collection and Repository
- Change the return type of `createById` to `DocumentId` to match the return type convention of the `DocCreate` abstract class
- Have `updateOrCreate` return `T` since it can create a class that didn't exist before (also follows the return type convention for the rule abstract class it now resides in`
- Bump dependencies
- Pass through all `Collection` methods through …

feat!: Sync Methods Between Collection and Repository

---

packages/firefuel/lib/firefuel.dart
packages/firefuel/lib/src/clause.dart
packages/firefuel/lib/src/firefuel_collection.dart
packages/firefuel/lib/src/firefuel_repository.dart
packages/firefuel/lib/src/rules.dart
packages/firefuel/lib/src/snapshot_conversion_mixin.dart
packages/firefuel/lib/src/utils/exceptions.dart
packages/firefuel/test/mocks/mock_collection.dart
packages/firefuel/test/src/firefuel_collection_test.dart
packages/firefuel/test/src/firefuel_repository_test.dart
packages/firefuel_env/pubspec.lock

Resolves [Issue #16](https://github.com/SupposedlySam/firefuel/issues/16#issue-989232363)
To get a subset of the documents inside a collection, currently you need to do something like this
```dart
final snapshot = await myCollection.ref.where('myField', isEqualTo: 'myValue').get();
return shapshot.docs.map((doc) => doc.data()).whereType<T>().toList();
```
^this is way too verbose to be doing every time you want to filter your collection.
- Create a `Clause` class to mimic the current `where` function on a `CollectionReference` and `Query`
- Add a `where` method to Collection (pass through to Repo) that returns a `Future<List<T>>` and accepts a `List<Clause>`.
- Add a `listenWhere` method to Collection (pass through to Repo) that returns a `Stream<List<T>>` and accepts a `List<Clause>`. …

feat: add where and listenWhere to Collection/Repo

---

packages/firefuel/lib/firefuel.dart
packages/firefuel/lib/src/chunk.dart
packages/firefuel/lib/src/collection.dart
packages/firefuel/lib/src/firefuel_collection.dart
packages/firefuel/lib/src/firefuel_repository.dart
packages/firefuel/lib/src/repository.dart
packages/firefuel/lib/src/rules.dart
packages/firefuel/lib/src/utils/query_extensions.dart
packages/firefuel/test/mocks/mock_collection.dart
packages/firefuel/test/src/firefuel_collection_test.dart
packages/firefuel/test/src/firefuel_repository_test.dart
packages/firefuel/test/src/utils/query_extensions_test.dart

Resolves #26 
Users need the ability to paginate their collections
- Create a `Chunk` class that contains all the information necessary to start, continue, and end pagination of the collection
- Add a `paginate` method that returns a `Chunk` to be passed back in when needed
- Pass through to repo

feat: add pagination ability

---

packages/firefuel/lib/src/firefuel_collection.dart
packages/firefuel/lib/src/firefuel_repository.dart
packages/firefuel/lib/src/rules.dart
packages/firefuel/test/mocks/mock_collection.dart
packages/firefuel/test/src/firefuel_collection_test.dart
packages/firefuel/test/src/firefuel_repository_test.dart

[Project Card Link](https://github.com/SupposedlySam/firefuel/issues/17)
There wasn't a readAll, which retrieves all docs from a collection.
Create a new method called `readAll`.

feat: Create #readAll

---

packages/firefuel/lib/src/firefuel.dart
packages/firefuel/lib/src/firefuel_collection.dart
packages/firefuel/test/src/firefuel_test.dart

[Project Card Link](https://github.com/SupposedlySam/firefuel/issues/30)
Add the ability for env collections
Add `env` to `Firefuel.initialize`
Prepend `env` to collection path in constructor

feat: Add collection prefix

---

packages/firefuel/lib/src/firefuel_collection.dart
packages/firefuel/test/src/firefuel_collection_test.dart

[Project Card Link](https://github.com/SupposedlySam/firefuel/issues/46)
Resolves Issue #46 
The only way to create a document id is by calling `collection.ref.doc().id`. This can get kinda lengthy.
Create a `generateDocumentId` method that will return unique `DocumentId`

feat: Create generate document id

---

packages/firefuel_core/lib/src/failure.dart
packages/firefuel_core/pubspec.lock
packages/firefuel_core/pubspec.yaml

[Project Card Link](https://github.com/SupposedlySam/firefuel/projects/1#card-71865463)
Resolves #50 
We are importing dart:io in the `Failure` class which isn't compatible with the web.  
Depend on universal_io and switch out the import for dart:io

feat: [package:firefuel_core] add universal_io to support web

---

packages/firefuel/lib/src/utils/file_path_util.dart
packages/firefuel/pubspec.lock
packages/firefuel/pubspec.yaml
packages/firefuel/test/utils/fixture_reader.dart
packages/firefuel/test/utils/test_path.dart

[Project Card Link](https://github.com/SupposedlySam/firefuel/projects/1#card-71865463)
Resolves #50 
Although we aren't using the FilePathUtil class, it was importing dart:io which isn't compatible on the web. Removing this should allow web support.
Replace the import to dart:io with universal_io//io

feat: [package:firefuel] add universal io to support web

---

packages/firefuel/lib/src/firefuel_fetch_mixin.dart

We were incorrectly using the current stack trace inside of the catch rather than using the one passed to us from the actual failure
Use the stack trace from the try to create a chain

fix: use stack trace from try failure

---

packages/firefuel/CHANGELOG.md
packages/firefuel/lib/src/collection.dart
packages/firefuel/lib/src/firefuel_collection.dart
packages/firefuel/lib/src/firefuel_repository.dart
packages/firefuel/lib/src/repository.dart
packages/firefuel/lib/src/rules.dart
packages/firefuel/pubspec.yaml
packages/firefuel/test/src/firefuel_collection_test.dart

[Project Card Link]()
Adds:
- `count`
- `countWhere`
- `streamCount`
- `streamCountWhere`
Use v4 of `cloud_firestore` to expose access to the new `count` function for `count` and `countWhere`. Provide access to a continually updated count through snapshots.

feat: add count, countWhere, streamCount, and streamCountWhere

---

.gitignore
docs/firefuelbrick.md
packages/firefuel/CHANGELOG.md
packages/firefuel/bricks/firefuel/README.md
packages/firefuel/bricks/firefuel/brick.yaml
packages/firefuel/mason-lock.json
packages/firefuel/mason.yaml

Docs need to be updated to show how to get the firefuel brick from BrickHub
Update readme and docs to reflect changes of getting the firefuel brick via `mason add firefuel` instead of through a git url.

docs: firefuel brick after package release

---

.gitignore
packages/firefuel/CHANGELOG.md
packages/firefuel/example/packages/firefuel_counter/pubspec.lock
packages/firefuel/example/pubspec.lock
packages/firefuel/lib/src/firefuel_collection.dart
packages/firefuel/lib/src/firefuel_repository.dart
packages/firefuel/lib/src/rules.dart
packages/firefuel/pubspec.yaml
packages/firefuel/test/src/firefuel_collection_test.dart

refactor!: renames `count` and `streamCount` to `countAll` and `streamCountAll`
Be more explicit, aligns with other methods such as `readAll` and `streamAll`, and leads us to look for other options like `countWhere` and `streamCountWhere` when using it in our apps.
Rename `count` and `streamCount` to `countAll` and `streamCountAll`

refactor!: rename count methods for consistency
